# 3. Service for both deployments
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  labels:
    app: recommendation
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: recommendation