# service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: ecommerce
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: ecommerce
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: ecommerce
