apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    name: ecommerce
    environment: production
    app.kubernetes.io/name: ecommerce
    app.kubernetes.io/part-of: microservices
    istio-injection: enabled  # This enables automatic Istio sidecar injection