# APISIX Global Plugins Configuration
# These plugins apply to all routes unless overridden

apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-global-plugins
  namespace: apisix
data:
  global-rules.json: |
    {
      "plugins": {
        "prometheus": {
          "prefer_name": true
        },
        "zipkin": {
          "endpoint": "http://jaeger-collector.istio-system.svc.cluster.local:9411/api/v2/spans",
          "sample_ratio": 1,
          "service_name": "APISIX"
        },
        "request-id": {
          "header_name": "X-Request-Id",
          "include_in_response": true
        },
        "real-ip": {
          "source": "http_x_forwarded_for",
          "trusted_addresses": ["0.0.0.0/0"]
        }
      }
    }
---
# API Key Authentication Consumer
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-consumers
  namespace: apisix
data:
  consumer-api-user.json: |
    {
      "username": "api-user",
      "plugins": {
        "key-auth": {
          "key": "apikey-12345678901234567890"
        },
        "limit-count": {
          "count": 1000,
          "time_window": 3600,
          "rejected_code": 429,
          "rejected_msg": "Consumer rate limit exceeded"
        }
      }
    }
  
  consumer-premium-user.json: |
    {
      "username": "premium-user",
      "plugins": {
        "key-auth": {
          "key": "premium-key-abcdefghijklmnop"
        },
        "limit-count": {
          "count": 5000,
          "time_window": 3600,
          "rejected_code": 429
        }
      }
    }
---
# APISIX Plugin Metadata
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-plugin-metadata
  namespace: apisix
data:
  # Prometheus plugin metadata
  prometheus-metadata.json: |
    {
      "log_format": {
        "$remote_addr": "remote_addr",
        "$remote_user": "remote_user",
        "$time_local": "time_local",
        "$request": "request",
        "$status": "status",
        "$body_bytes_sent": "body_bytes_sent",
        "$http_referer": "http_referer",
        "$http_user_agent": "http_user_agent",
        "$http_x_forwarded_for": "http_x_forwarded_for"
      }
    }
  
  # Error log format
  error-log-metadata.json: |
    {
      "log_format": {
        "host": "$host",
        "client": "$remote_addr",
        "scheme": "$scheme",
        "request": "$request",
        "request_time": "$request_time",
        "status": "$status",
        "bytes_sent": "$bytes_sent",
        "upstream_addr": "$upstream_addr",
        "upstream_status": "$upstream_status",
        "upstream_response_time": "$upstream_response_time"
      }
    }
---
# APISIX Service with ExternalName pointing to Istio services
# This enables APISIX to route to services in the Istio mesh
apiVersion: v1
kind: Service
metadata:
  name: bookinfo-productpage
  namespace: apisix
spec:
  type: ExternalName
  externalName: productpage.bookinfo.svc.cluster.local
  ports:
    - port: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: bookinfo-reviews
  namespace: apisix
spec:
  type: ExternalName
  externalName: reviews.bookinfo.svc.cluster.local
  ports:
    - port: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: bookinfo-ratings
  namespace: apisix
spec:
  type: ExternalName
  externalName: ratings.bookinfo.svc.cluster.local
  ports:
    - port: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: bookinfo-details
  namespace: apisix
spec:
  type: ExternalName
  externalName: details.bookinfo.svc.cluster.local
  ports:
    - port: 9080
